### ISSUE TITLE
Cannot change locale for aurelia-bootstrap-datepicker

### ISSUE THREAD

**Issue by codeflowee** [ghiscoding/Aurelia-Bootstrap-Plugins#12]
In my view:
```html
<abp-datetime-picker value.bind="date" options.bind="{ format: 'DD-MM-YYYY', maxDate: 'now', locale: 'fi' }"></abp-datetime-picker>
```

Error in console:
```
Uncaught TypeError: locale() locale fi is not loaded from moment locales!
```

**Comment by ghiscoding** [comment]
Are you sure that your moment locale is installed? What happens when you do  this in your ViewModel
```javascript
moment.locale('fi');
console.log(moment(1316116057189).fromNow());
moment.locale('en');
console.log(moment(1316116057189).fromNow()); // an hour ago
```

What skeleton are you using, `CLI`, `WebPack` or `ASP`?
Please provide more details about your setup, if you want help.

**Comment by codeflowee** [comment]
I am using `aurelia-cli` type project:

In view-model when I import moment via `import moment from 'moment';` then in constructor the response for
```javascript
    moment.locale('fi');
    console.log(moment(1316116057189).fromNow());
    moment.locale('en');
    console.log(moment(1316116057189).fromNow());
```
is
```
6 years ago
6 years ago
```

In `aurelia.json` I have following for this plugin:
```json
{
  "name": "eonasdan-bootstrap-datetimepicker",
  "path": "../node_modules/eonasdan-bootstrap-datetimepicker/build",
  "main": "js/bootstrap-datetimepicker.min",
  "resources": [
    "css/bootstrap-datetimepicker.min.css"
  ]
},
{
  "name": "aurelia-bootstrap-datetimepicker",
  "path": "../node_modules/aurelia-bootstrap-datetimepicker/dist/amd",
  "main": "index",
  "resources": [
    "**/*.{css,html}"
  ]
},
"moment"
```

**Comment by codeflowee** [comment]
Okay, thanks for leading me on the right way:

What needed for this fix was:
```json
{
  "name": "moment",
  "path": "../node_modules/moment",
  "main": "min/moment-with-locales"
}
```
in `aurelia.json`

This should be added into "How to" docs.

**Comment by ghiscoding** [comment]
Thanks a lot for the feedback, I added a note in the README under the `Aurelia-CLI` section of the [aurelia-bootstrap-datetimepicker](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-datetimepicker#cli) plugin. Also made it more clear under the `WebPack` version as well.

**Comment by codeflowee** [comment]
Thanks, keep up the good work! :+1:

**Comment by ghiscoding** [comment]
No problem, if you like the plugin, you can also click on the :star: to make it more popular :)
