### ISSUE TITLE
Adding showClear: true option returns Invalid date when trying to clear

### ISSUE THREAD

**Issue by codeflowee** [ghiscoding/Aurelia-Bootstrap-Plugins#15]
Currently there is a bug when clearing an input value, when I first choose a date from calendar and then try to clear, it returns first `Invalid date`, after focusing out and then focusing input again it seem to clear it.

**Comment by ghiscoding** [comment]
Can you tell me the error shown in the console? It might be related to #13 which I will review in the weekend (tomorrow)

**Comment by ghiscoding** [comment]
Could you also tell me the code you use to clear. Are you clearing with the `model.bind` or the `value.bind` and is just a `null` that you send to clear?

**Comment by ghiscoding** [comment]
This should be fixed now with the suggestion provided in #14.
Please update to latest [NPM version 1.0.8](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker)

If it's still an issue, please provide more details or open another issue. Thanks
