### ISSUE TITLE
Error when binding value only

### ISSUE THREAD

**Issue by zurfluh** [ghiscoding/Aurelia-Bootstrap-Plugins#20]
**Steps to reproduce**
_aurelia-bootstrap-datetimepicker NPM 1.0.9_

Date picker with value only:
```
<abp-datetime-picker value.bind="myData.release.myDate"
                        options.bind="{ format: 'DD.MM.YYYY' }"></abp-datetime-picker>
```
Setting the value in the activate() function of the view model (e.g. a dialog):
```
export class DetailsDialog {
    myData: Data;
    
    constructor(private dialogController: DialogController) {}

    activate(d: Data) {
        this.myData = d;
        // This is always a string in a valid format, e.g. '30.06.2017':
        this.myData.release.myDate = this.myData.endDate; 
    }
}
```
**Expected**: no exception
**Actual**

![image](https://user-images.githubusercontent.com/2371518/27742341-95832d6a-5db8-11e7-96dc-fb5899dc0543.png)
**Additional Info**
![image](https://user-images.githubusercontent.com/2371518/27742400-c43480a0-5db8-11e7-9885-af6f9cee7027.png)

**Comment by ghiscoding** [comment]
I think that it would only work with `value.bind` since `model.bind` should always be a `Date` object and in your case it's not, it's just a String. As shown in the README

```javascript
value.bind="dateEntered" // output --> 2005-05-05 10:00
model.bind="dateObject"  // output --> Thu May 05 2005 10:00:00 GMT-0400 (Eastern Daylight Time)
```

**Comment by zurfluh** [comment]
I do not quite understand. I _am_ using `value.bind`. And I use it exactly as described in the [first section](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-datetimepicker#usage) of the readme/documentation. The error occuring in `modelChanged()` may be some (side) effect.

The readme clearly claims that value is two-way bound. My assigning a value (`this.myData.release.myDate = this.myData.endDate;`) triggers this bug.

**Comment by ghiscoding** [comment]
Ah sorry, I read it too fast, I'm at work and the time is short. Could you try using a format like describe in my example just to see if that work. With the following `options.bind="{ format: 'YYYY-MM-DD' }"` and a date like `2005-05-05`. I just want to sure that it works this way before going further. 

Are you using at all `model.bind`? I don't see it in your sample but still would like to confirm. Since the error is thrown from `modelChanged`, I'd like to know from where exactly it starts.

**Comment by ghiscoding** [comment]
Fixed, your issue was caused by a custom format, it now support any format. Please use latest [version 1.0.10](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker)

**Comment by zurfluh** [comment]
Thanks a lot for the fast fix! It works now as desired.
