### ISSUE TITLE
Aurelia-bootstrap-datetimepicker element.bind undefined

### ISSUE THREAD

**Issue by eramella** [ghiscoding/Aurelia-Bootstrap-Plugins#24]
I am trying to attach a function to the onChange event of the element, but the element stays undefined at all stages of the view lifecycle.  The abp-datetime-picker element is in my view and works perfectly, I included the element.bind="picker", picker is a variable in my vewmodel. I tried to access this variable in the constructor, at bind and at attached but it is always undefined. 
Instead if I wait for the entire view to be loaded and functional and then I manually click a button to fire the function that calls:
this.picker.events.onChange = (e) => console.log('onChange');
all works just fine.
Any idea on where I can hook my onChange function?

**Comment by ghiscoding** [comment]
It make senses that the picker must be loaded completely before any events are available. The events are only expose on the `attached()` function as shown [here](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/blob/master/aurelia-bootstrap-datetimepicker/src/abp-datetime-picker.js#L55). If you define that in your constructor, it's probably too early and the plugin won't know about it, there's no preconfig saved anywhere (except global configuration which is for all pickers).

**Comment by eramella** [comment]
I agree with you and that is why it seems weird. The onChange function assignment IS in the attached call back, but the element is undefined there. I might have to put a setTimeout to the this.picker.events.onChange = (e) => console.log('onChange');
and hopefully the element becomes available. it is strange. I am assuming Aurelia runs all the attached call back of the custom elements first before running the attached call back of the view.

**Comment by ghiscoding** [comment]
I didn't see any issues with my samples though, for example the [client-wp (WebPack)](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/client-wp). I have it implemented with what is shown in the README and I don't think that I've seen any undefined. However, I didn't put the `onChange` event in the constructor, it's really outside of it, I don't think it should go in the constructor anyway.

**Comment by eramella** [comment]
I am sorry, I am probably missing something here. who is calling the pickerChanged() function? when I added it to my viewmodel it was never called ....am I missing something here

**Comment by ghiscoding** [comment]
Can you review my sample(s) that are part of this Github repo and see if your code is different or similar? That's the main reason I created and provided these samples, to help others in using it and troubleshooting

**Comment by eramella** [comment]
Thank you for your patience and help, I figure it out. I was not connecting the element.bind to "picker" and the "pickerChanged" relationship. I was not aware that you can add the word Changed to a bindable property name and have a callback on binding, which does the trick and it is called after attached. This is all Aurelia behavior and has nothing to do with your great job on these plugins. 
Just in case others might miss this detail and find themselves in this same issue, I would suggest to add a small note on the docs "Available Methods/Functions" section to explain.

**Comment by ghiscoding** [comment]
Great you found the solution. For the note, there's already a `pickerChanged()` function shown in that section, that should suffice. Thanks for the feedback 

If you like the plugin, you can also upvote 👍  ⭐️ 
Enjoy
