### ISSUE TITLE
abp-datetime-picker - Can't select maximum date initially, can after choosing alternative date

### ISSUE THREAD

**Issue by danjayne** [ghiscoding/Aurelia-Bootstrap-Plugins#26]
If the max date is say 23rd August 2017 and I load my page and select that date, I am able to click the item (not prevented from clicking it) but the value is not bound. 

If I instead choose a different date (23rd August 2017) and then choose the max date afterwards, the binding happens correctly. 

I've not looked into the source to work out why this isn't working, just thought I would make you aware.

Cheers.

**Comment by ghiscoding** [comment]
Could you please provide the View html code and ViewModel options that you used. This will make it easier to troubleshoot later. Thanks

**Comment by ghiscoding** [comment]
Unless you provide me your code sample, as I requested you a few days ago, I don't see any problems with the plugin when I enter the option in the View.

It all works for me, if my View has the following (with a `maxDate` of '2017-08-29')
```html
<abp-datetime-picker element.bind="picker" value.bind="activeDate" options.bind="{ maxDate: '2017-08-29', showClear: true, showTodayButton: true, format: 'YYYY-MM-DD' }"></abp-datetime-picker>
```
The UI properly blocks me from clicking that date 
![maxdateinview](https://user-images.githubusercontent.com/643976/29745166-e96f1e34-8a81-11e7-9073-4a5f7e8d03a5.png)

**EDIT**
Also tried moving the options from the View to the ViewController and it still works
`View`
```html
<abp-datetime-picker element.bind="picker" value.bind="activeDate" options.bind="dateOptions"></abp-datetime-picker>
```
`ViewController`
```javascript
export class MyViewController {

  dateOptions = { 
    showClear: true, showTodayButton: true, format: 'YYYY-MM-DD', maxDate: '2017-08-29' 
  }
}
```

**Comment by danjayne** [comment]
Hi,

Sorry I didn't get back in touch.

I don't have access to the code right now as I'm not in work.

I was using the following:

Max date - Moment()

Then the first time I clicked today's date it didn't work. I know why now.
It's because moment includes time, not just the date part.

This isn't an issue for me that I need solved, I was just letting you know.
Thanks for getting back to me

Daniel



On 26 Aug 2017 10:15 p.m., "Ghislain B." <notifications@github.com> wrote:

Unless you provide me your code sample, as I requested you few days ago, I
don't see any problems with the pluging.

It all works for me, if my View has the following (with a maxDate of
'2017-08-29')

<abp-datetime-picker element.bind="picker" value.bind="activeDate"
options.bind="{ maxDate: '2017-08-29', showClear: true,
showTodayButton: true, format: 'YYYY-MM-DD' }"></abp-datetime-picker>

The UI properly blocks me from clicking that date
[image: maxdateinview]
<https://user-images.githubusercontent.com/643976/29745166-e96f1e34-8a81-11e7-9073-4a5f7e8d03a5.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/issues/26#issuecomment-325162307>,
or mute the thread

**Comment by ghiscoding** [comment]
Reviewing open issues and coming back to this, I tried with `maxDate: moment()` and again it works. 
This is what I used to test:
```html
<abp-datetime-picker element.bind="picker5" value.bind="date5" options.bind="dateOptions5"></abp-datetime-picker>
```
and in the ViewController
```javascript
dateOptions5 = { 
    showClear: true, showTodayButton: true, format: 'YYYY-MM-DD', maxDate: moment() 
  }
```
![maxdate](https://user-images.githubusercontent.com/643976/30514585-fb91cfc0-9ae5-11e7-9368-afa9b9a93943.png)


So I will close this issue, unless you provide a real example. If it's really a problem that can be identified, then we can revisit and reopen the issue if necessary. Please next time provide a full example so that it makes it easier for all of us. Thanks
