### ISSUE TITLE
Using an array of objects with tag-input does not appear to work.

### ISSUE THREAD

**Issue by matthewh** [ghiscoding/Aurelia-Bootstrap-Plugins#31]
Starting from your example in https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/client-cli, I tried the various approaches mentioned in the documentation to get an array of objects to render with the tag input. I was not successful. Is there a bug? Am I doing something wrong?

1. Modified bootstrap-plugins.html to bind options
```
<abp-tags-input element.bind="tag" value.bind="post.categories" options.bind="tagOptions" placeholder="enter a category tag"></abp-tags-input>
```

2. Modified bootstrap-plugins.js to add options and define objects.

```
  constructor() {
    this.post = {
      categories: [{value:'1', text: 'Javascript'} , {value:'2', text:'C#'}]
    };
    this.tagOptions = {
        itemText:'text',
        itemValue: 'value'
    };

...
```

**Comment by ghiscoding** [comment]
This is the exact same as #28 and is unfortunately out of my control as it is an issue with the `Bootstrap-Tagsinput` itself. Please refer to that issue #28 for more details

**Comment by ghiscoding** [comment]
I added a [notice](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-tagsinput#important-note) on the front page. It's just too bad that it's a bug within the external lib, but there isn't much I can do, sorry. However, array of strings are working correctly and are the way to go.

**Comment by matthewh** [comment]
Thank you for adding the note and pointing me to the issue.
