### ISSUE TITLE
AbpDatetimePickerCustomElement.showCalendar -Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by ayaanraj** [ghiscoding/Aurelia-Bootstrap-Plugins#38]
I'm using Aurelia-skeleton-esnext and bootstrap v4.
And I have configured the plugin as below:
In main.js:
```javascript
.plugin('aurelia-bootstrap-datetimepicker', config => {
      // extra attributes, with config.extra
      config.extra.iconBase = 'font-awesome';
      config.extra.withDateIcon = true;
      // or any picker options, with config.options
      config.options.showClear = true;
      
      // or any picker options, with config.options
      config.options.showTodayButton = true;
      
      // or any picker options, with config.options
      config.options.format = 'DD-MM-YYYY';
      
      // or any picker options, with config.options
      config.options.allowInputToggle = true;

      // if you use Bootstrap 4 Beta 3
      config.extra.bootstrapVersion = 4;

      // you can also change the Bootstrap 4 button class, default is shown below
      config.extra.buttonClass = 'btn btn-outline-secondary';
    })
```
So, when I click on Calender-Icon, it show the error:
*AbpDatetimePickerCustomElement.showCalendar** -Cannot read property 'data' of undefined*

**Comment by ghiscoding** [comment]
Please provide more info and ways to reproduce, also include your View code

**Comment by ayaanraj** [comment]
This is my view code :

`<abp-datetime-picker value.bind="dob & validate "></abp-datetime-picker>`

For the first time, their is no problem, I mean to say, when I navigate from home route to the page where dateTimePicker located.
But the problem rises when I navigate to some other route, from the page where dateTimePicker located and come back to the dateTimePicker located  page, then again, when I click on calendar icon, it throws error which i have mentioned.
And also If I'm not using the calendar-icon, the other way to show calendar is, when input element gets the focus, while this also, it throws same error as mentioned.
`
AbpDatetimePickerCustomElement.prototype.showCalendar = function showCalendar() {
      this.domElm.data('DateTimePicker').show();
};
`
the above function throws the error and when I check the value of this.domElm is undefined

**Comment by ayaanraj** [comment]
Hey, that error was due some binding issue in application, And their is no issue with this plugin, so closing this issue

**Comment by ghiscoding** [comment]
Awesome, thanks for letting me know, less troubleshooting time :)
