### ISSUE TITLE
disable date-picker on readonly

### ISSUE THREAD

**Issue by pnguyen535** [ghiscoding/Aurelia-Bootstrap-Plugins#41]
Hello, 

Thanks for making a great date-picker. I think this is the best one I have found so far. However, I want to make a request to turn off the date picker if "readonly is set on the input.

Thanks

**Comment by ghiscoding** [comment]
Pushed a new version `1.1.2` on [NPM](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker), you can add `readonly.bind="true"` and you also need to use the picker option `ignoreReadonly: true`, see the [demo](https://ghiscoding.github.io/Aurelia-Bootstrap-Plugins/#/bootstrap-plugins/datetime-picker) for an example.

Also upvote ⭐️ if you like the lib. Thanks

**Comment by pnguyen535** [comment]
Thanks Ghislain for the quick response. However, the behavior is not what I expecting. I was thinking if the datepicker is set to "ReadOnly", it should not show the datepicker calendar to the user. Can you update the code?

**Comment by ghiscoding** [comment]
It is the behavior you want, just don't enable the picker option `ignoreReadonly: false` (which is the default anyway). I don't need to change the code.

**Comment by pnguyen535** [comment]
Thanks, it works perfectly
