### ISSUE TITLE
DateTimePicker Font Awesome 5

### ISSUE THREAD

**Issue by Cali03** [ghiscoding/Aurelia-Bootstrap-Plugins#42]
Hi,

It's possible have compatibility with Font Awesome 5?

Thanks

**Comment by ghiscoding** [comment]
I'm not using the latest version of Font Awesome but PR (Pull Request) are welcome

**Comment by Cali03** [comment]
Hi,

Here you have ;)

Thanks

**Comment by ghiscoding** [comment]
So I guess we can close this issue since I merged and released a new version? You can also upvote ⭐️  if you like the lib

**Comment by Cali03** [comment]
Hi,

Yes we can close it :).
About the upvote because i like the lib and use it i just give you a star ;)

Thanks
