### ISSUE TITLE
Startup problems after dependency "bootstrap-select" was updated to 1.13.0

### ISSUE THREAD

**Issue by Melfi11** [ghiscoding/Aurelia-Bootstrap-Plugins#46]
Bootstrap-select was updated on 19th of april to the new release version v1.13.0.

https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0

Within aurelia-bootstrap-select there is the dependency to bootstrap-select (latest minor-version) in the package-json:

`"bootstrap-select": "^1.12.2",`

So it will pull the new release.
With this release we´ve got some problems in our aurelia-applications:

1. Startup issue - cannot read property 'Constructor' of undefined

![image](https://user-images.githubusercontent.com/38665702/39140924-5f271846-4726-11e8-80db-58ac95e11aef.png)

2.  in another application the display of the select-picker crashed:

![image](https://user-images.githubusercontent.com/38665702/39141286-a89204e0-4727-11e8-9df7-ba85a2edc897.png)

3. On getting the selected value the page hangs up with following error message:

![image](https://user-images.githubusercontent.com/38665702/39141353-dbd7d08c-4727-11e8-8a82-cb9308621a15.png)

If i set back the version of the dependency bootstrap-select to the last patch-version everything is fine and all of these errors are gone.
I set the version of the dependency in my local copy of the plugin in the node-modules folder:

`"bootstrap-select": "~1.12.2",`

**Comment by ghiscoding** [comment]
ok thanks for the detailed explanation. I'm currently in vacations and will get to it when I get back.

**Comment by ghiscoding** [comment]
Pushed a new version `1.1.3` on [NPM](https://www.npmjs.com/package/aurelia-bootstrap-select)
Would you mind verifying it before closing the issue? 

Thanks for the feedback

**Comment by ghiscoding** [comment]
no news, good news. I will consider this as now working
