### ISSUE TITLE
Clear Date Picker Value from custom Function

### ISSUE THREAD

**Issue by ayaanraj** [ghiscoding/Aurelia-Bootstrap-Plugins#47]
I need to clear or set datepicker value to default, with out clicking on delete icon from the calendar from my custom function.

**Comment by ghiscoding** [comment]
You should be able to do that with the [Available Methods](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-datetimepicker#available-methodsfunctions)

**Comment by ayaanraj** [comment]
thanks

**Comment by ghiscoding** [comment]
Welcome, you can also upvote ⭐️ if you like the lib. Cheers
