### ISSUE TITLE
abp-datetime-picker - input with keyboard

### ISSUE THREAD

**Issue by thejaff2** [ghiscoding/Aurelia-Bootstrap-Plugins#5]
Request/bug? I am trying to write a new date in the input field using the keyboard but it immediately goes to "Invalid date" with an error in the console with no way to keep writing (only to select with mouse). I have tried using the "keepInvalid" option but to no avail.

**Comment by ghiscoding** [comment]
Will have to review this in the weekend, can you attach a print screen of a copy+paste of the error you got. Thanks

**Comment by ghiscoding** [comment]
Looked at it tonight, and found the issue, I added more checks in place. Like an `isValid()` check of the `moment` date **before** actually trying to convert it (which was my mistake). Hopefully everything works fine now, so sorry about that, spent too much time on the other plugin. Thanks for all the feedback, feel free to reach out if something else is wrong.

Thanks again
