### ISSUE TITLE
Enable User to Manually Enter Date from KeyBoard

### ISSUE THREAD

**Issue by ayaanraj** [ghiscoding/Aurelia-Bootstrap-Plugins#57]
I have this requirement, were user wants to enter the date manually rather than using picker, which is provided.
I have seen the documentation and have gone through bootstrap datetimepicker also, but I couldn't found anything.
please help me out, with this.

**Comment by ghiscoding** [comment]
Just open the input for typing and that will let your user type a date, but you will have to provide proper validation.

Just remember that this plugin is a wrapper of the original picker, it is supposed to be at equality in terms of what it can do (not more, not less), but if you can't find it in the original than you won't find it in this plugin either

**Comment by ayaanraj** [comment]
Thanks @ghiscoding.
I have used value converter along with datetimepicker, which was giving some other behaviour.

**Comment by ghiscoding** [comment]
Sorry for the late reply but I don't think it's a problem with this lib itself. 
I think you can just disable this flag (which is enable in the lib)

```javascript
allowInputToggle: false
```

See the official [doc](https://eonasdan.github.io/bootstrap-datetimepicker/Options/#allowinputtoggle)

**Comment by ghiscoding** [comment]
closing as no feedback and solution was provided
