### ISSUE TITLE
add new item 

### ISSUE THREAD

**Issue by johntom** [ghiscoding/Aurelia-Bootstrap-Plugins#64]
Hi,
It would be a great feature to add a new item to select list.
John
ie. list has apples, oranges, pears
when you type in grapes it would add it to the select list 
see https://select2.org/tagging Dynamic option creation for ref

**Comment by ghiscoding** [comment]
I don't really understand your question, but if you just want to add something to the list then just modify the array and that's it, you can see this in the [demo](https://ghiscoding.github.io/Aurelia-Bootstrap-Plugins/#/bootstrap-plugins/bootstrap-select) and click on "Change Collection" on the first dropdown. 

I must say that this lib is a wrapper of `Bootstrap-Select`, if that lib can do what you're asking for, then this plugin can probably do it as well. However what you show (`select2`) is a totally different lib that has nothing to do with my plugin

**Comment by ghiscoding** [comment]
Closing as no feedback was provided and the lib already support adding item(s) to the collection which will re-render the select element.
