### ISSUE TITLE
Target Bootstrap 4 with the select?

### ISSUE THREAD

**Issue by jasonhjohnson** [ghiscoding/Aurelia-Bootstrap-Plugins#66]
Hi,

I see it's possible to target bootstrap 4 with the timepicker but is there a way to do this from main.js with the select?

Thanks,
Jason

**Comment by ghiscoding** [comment]
I did not have the time to switch to the new version of [Bootstrap-Select](https://developer.snapappointments.com/bootstrap-select/) (PRs are welcome though), however I provided an extra CSS file to use that works in Bootstrap 4, all the info is already in the [README](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-select#aurelia-mainjs)

**Comment by jasonhjohnson** [comment]
Any chance we could do a webex for a minute? I want to make sure I'm using it right?

**Comment by ghiscoding** [comment]
Sorry but I'm at work and this lib is Open Source and provided as is. Please try using it first and if there's something you can't understand then write a comment and I will try to reply if I can.

**Comment by ghiscoding** [comment]
closing as no feedback and possibly no problem with the lib itself. I can re-open if necessary
