### ISSUE TITLE
abs-select - Optgroup doesn't work if there are fewer options than the group index

### ISSUE THREAD

**Issue by jmurphy-riskexec** [ghiscoding/Aurelia-Bootstrap-Plugins#68]
In the aurelia-bootstrap-select the group options are being fetched using `getMappingPropertyValueFromIndex`, which is passed the `$index` from `group of getGroupedCollection()`.  So if the third group has only one element, the label for that group winds up empty.

The fix is to pull the options from the first element of the group.

**Comment by ghiscoding** [comment]
Can you provide an example with an array of `optgroup` mapping that would cause this behavior? I'd like to visualize the problem and make sure that it works as expected.

**Comment by jmurphy-riskexec** [comment]
Sure. I updated my PR with a repro on your sample page.  The third group only has one item, so the label is omitted.

**Comment by ghiscoding** [comment]
closed by your PR #69, thanks for that.
I released a new `major` version `1.4.0` on [NPM](https://www.npmjs.com/package/aurelia-bootstrap-select) mainly because I don't how to fully test it, so I prefer a major just in case. 

Again thanks for the PR and ⭐️  cheers
