### ISSUE TITLE
Aurelia Boostrap Select - Infinite loop on object with id=0 selection

### ISSUE THREAD

**Issue by czeslav87** [ghiscoding/Aurelia-Bootstrap-Plugins#78]
Hello,

We've came across bug using aurelia-bootstrap-select. Whenever we pass collection with object.id=0 browser freezes due to infinite loop.

I've located issue on line 483:
`var selection = this.findItems(this.collection, newValue || this._originalSelectedObjects, this.objectKey);`

error conditions:
`newValue = 0`

issue root:
`newValue || this._originalSelectedObjects` returns null instead of 0.

suggested fix:
`var selection = this.findItems(this.collection, (newValue !== null && newValue !== undefined) ? newValue : this._originalSelectedObjects, this.objectKey);`

Best regards,
Maciej

**Comment by ghiscoding** [comment]
Should be fixed with latest version `1.4.1`, thanks a lot for providing a solution. 
Also updated demo with collections having 0 as `id`

You can also up vote if you haven't already ⭐️ 
Thanks
