### ISSUE TITLE
Select - Missing methods

### ISSUE THREAD

**Issue by VitriolCZ** [ghiscoding/Aurelia-Bootstrap-Plugins#79]
I am missing methods to programmatically show/hide selectpicker. Is possible to add them?

**Comment by ghiscoding** [comment]
Most probably doable, just use the core library methods to do so. 
Take a look at the [Available Methods](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-select#available-methodsfunctions) for how to use them

**Comment by ghiscoding** [comment]
Closing for no feedback provided
