### ISSUE TITLE
Not working well with custom format

### ISSUE THREAD

**Issue by cristhian-net** [ghiscoding/Aurelia-Bootstrap-Plugins#8]
I think it is a bug. My format is 'DD/MM/YYYY hh:mm A', but it throws an error every time I change the date, and causes model to be invalid date. So I have changed 1 line and now it is working. I will submit a PR. The code was not taking into account when a custom format was set (just calling moment(date).toDate()).

**Comment by cristhian-net** [comment]
PR submitted

**Comment by ghiscoding** [comment]
hello @CristhianUNSa thanks a lot for the PR, I will review it possibly tomorrow. Sorry about the delay as I was away in vacations for the past few weeks.

**Comment by cristhian-net** [comment]
@ghiscoding no problem, and thank you for your time :+1:

**Comment by ghiscoding** [comment]
Thanks for the Pull Request, I made a new release `1.0.6`, now updated on [NPM](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker). This new release include both `modelChanged` and `valueChanged` with a strict format changed. So thanks again :)

**Comment by cristhian-net** [comment]
@ghiscoding thanks I was waiting for it on npm ! :)

**Comment by ghiscoding** [comment]
Great, let me know if that fixes your issue. 
Thanks ;)
