### ISSUE TITLE
typing impossible

### ISSUE THREAD

**Issue by MenNoWar** [ghiscoding/Aurelia-Bootstrap-Plugins#83]
Due to the triggered update on every keypress, one can simply not type in a date.
Solution:  in the html-file replace the 
`value.bind="value" `
with
`value.two-way="value & updateTrigger:'blur'"`

to update on leaving the control only.

**Comment by ghiscoding** [comment]
PR are welcome if you think that you have a good working solution.

**Comment by ghiscoding** [comment]
I took your code and update the date picker input value bind. It's released under version `1.3.7` of the plugin, you can check [NPM](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker)
